apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  client.key.pem: {{ .Files.Get "secrets/client.key.pem" | b64enc }}
  client.cert.pem: {{ .Files.Get "secrets/client.cert.pem" | b64enc }}
  ca.cert.pem: {{ .Files.Get "secrets/ca.cert.pem" | b64enc }}
  taskd.server: {{ .Values.taskd.server | b64enc }}
  taskd.credentials: {{ .Values.taskd.credentials | b64enc }}
  smtp.appKey: {{ .Values.smtp.appKey | b64enc }}
  smtp.host: {{ .Values.smtp.host | b64enc }}
  smtp.port: {{ .Values.smtp.port | b64enc }}
  smtp.user: {{ .Values.smtp.user | b64enc }}
  smtp.from: {{ .Values.smtp.from | b64enc }}
  recipient: {{ .Values.recipient | b64enc }}
